$f: \mathbb{R} \rightarrow \mathbb{R}, f(x) = e^x $

In [ ]:
def schimbare(param1, param2):
    param2, param1 = param1, param2
    return param1, param2

#apelare functie
x, y = (int(x) for x in input().split())
print(*schimbare(x, y))

2 3
3 2


In [ ]:
def adun():
    print(x + 1)
x = 13
adun()
x = 19
adun()
x = 66
adun()

14
20
67


In [ ]:
def f1():
    x = 66
    def f2():
        y = x + 1
        print(y)
    f2()
    print(x)
f1()

67
66


In [ ]:
import math
import numpy as np
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print(print("sir"))
def corp_instructiuni():
    print()

sir
None


In [ ]:
def f(parametrul_1, parametrul_2):
    corp_instructiuni()
    return x
print()

In [ ]:
def paritate(x):
    if x % 2 == 1:
        return 'x impar'
    return 'x par'
print(paritate(3))
print(paritate(2))

x impar
x par


In [ ]:
def f(x, y, z):
    return x+y, y*x, x+z
s, p, s1 = f(1, 2, 3)
print(f(1, 2, 3))
print(s, p, s1)

(3, 2, 4)
3 2 4


In [ ]:
def f(x, y, z=24):
    return x+y+z

print(f(1, 2))
print(f(1, 2, 0))

27
3


In [ ]:
def suma(*t):
    s = 0
    for termen in t:
        s = s + termen
    return s
print(suma(1, 2, 3))
print(suma(2, 3, 5, 7, 11))
print(suma())

6
28
0


In [ ]:
def lista(ls):
    ls.append(3)
    ls = ls + [4, 5]
    return ls
ls = [1, 2]
print(lista(ls))
print(ls)

[1, 2, 3, 4, 5]
[1, 2, 3]


In [ ]:
def loco():
    x = 78
    y = 'trei'
    return str(x)+y
loco()
print(y)

NameError: name 'y' is not defined

In [ ]:
def rcd():
    print(x+1)

x = 7
rcd()

8


In [ ]:
def rcd():
    global x
    x = x + 1
    return x
x = 7
print(rcd())

8


In [ ]:
def f1():
    x = 7
    def f2():
        nonlocal x
        x = x + 1
        print(x)
    f2()
    print(x)
f1()

8
8


In [ ]:
def g(x):
    x = x + 29
    print(x)
    x = str(x) + 'marian'
    print(x)
    x = (str(x), list(x))
    return x
x = 0
print(g(x))
print(x)

29
29marian
('29marian', ['2', '9', 'm', 'a', 'r', 'i', 'a', 'n'])
0


In [ ]:
def h(ls):
    ls = ls.copy()
    ls.append(37)
    ls.reverse()
    print(ls)
ls = [1, 2, 3]
print(ls)
h(ls)
print(ls)

[1, 2, 3]
[37, 3, 2, 1]
[1, 2, 3]


In [ ]:
d = [['popescu', 9.56], ['ionescu', 6.44], ['andronescu', 8.37]]
print(sorted(d, key = lambda x: x[0]))

[['andronescu', 8.37], ['ionescu', 6.44], ['popescu', 9.56]]


In [ ]:
d = [['apopescu', 9.56], ['ionescu', 6.44], ['andronescu', 9.57]]
print(sorted(d, key = lambda x: (x[0][0], -x[1])))

[['andronescu', 9.57], ['apopescu', 9.56], ['ionescu', 6.44]]


---

# **Recursivitate**

## **Fibonacci**

In [ ]:
def fib(n):
    a = 0
    b = 1

    for _ in range(1, n):
        a, b = b, a + b

    return a

print(*[fib(x) for x in range(1, 15)])

0 1 1 2 3 5 8 13 21 34 55 89 144 233


In [ ]:
def fib_rec(n):
    if n == 1:
        return 0
    if n == 2:
        return 1

    return fib_rec(n - 1) + fib_rec(n - 2)

print(*[fib_rec(x) for x in range(1, 15)])

0 1 1 2 3 5 8 13 21 34 55 89 144 233


## **Factorial**

In [ ]:
def factorial(n):
    if n <= 1:
        return 1
    else:
        return n * factorial(n - 1)

print(factorial(5))

120


## **Suma unei liste**

In [ ]:
def suma_listei(lst):
    if not lst:
        return 0
    return lst[0] + suma_listei(lst[1:])

print(suma_listei([1, 2, 3, 4, 5, 6, 7]))

28


## **Print 1 to n**

In [ ]:
def print_1_to_n(n):
    if n == 0:
        return
    print_1_to_n(n - 1)
    print(n, end=" ")

print_1_to_n(10)


1 2 3 4 5 6 7 8 9 10 

## **Căutarea binară**

In [ ]:
def binary_search(lista, valoare):
    st = 0
    dr = len(lista) - 1
    while st <= dr:
        mij = st + (dr - st) // 2
        if lista[mij] == valoare:
            return mij
        elif lista[mij] < valoare:
            st = mij + 1
        else:
            dr = mij - 1

    return -1

v = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(binary_search(v, 2))

-1


In [ ]:
def bin_search_rec(lista, valoare, st, dr):
    if st > dr:
        return -1

    mij = st + (dr - st) // 2

    if lista[mij] == valoare:
        return mij
    elif lista[mij] < valoare:
        return bin_search_rec(lista, valoare, mij + 1, dr)
    else:
        return bin_search_rec(lista, valoare, st, mij - 1)

v = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(bin_search_rec(v, 2, 0, len(v) - 1))

1
